---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.11.1
  kernelspec:
    display_name: R
    language: R
    name: ir
output: 
  html_document:
    theme: spacelab
---

# Questionnaires

This analysis compares the results of STAI and SWE questionnaires between friend and stranger groups.

```{r, message=FALSE}
library('tidyverse')
library('afex')
library('emmeans')
library('BayesFactor')
library('ggpubr')
library('ini')
```


We are working with the following files:
```{r}
config <- read.ini("../config.ini")
tab_file <- file.path(config$DEFAULT$QUESTIONNAIRE_DIR, 'table.tsv')
```

The analysis is based on the observers:

```{r}
df <- read_tsv(tab_file, col_types=cols())
```

```{r}
df <- df %>%
    filter(role == "OBS") %>%            # observers only
    filter(group == "friend")            # friends only
```

## State anxiety

Data preparation & wide-format export for JASP:

```{r}
state_anxiety <- df %>% 
    select(c("label", starts_with("STAI_state"))) %>%
    pivot_longer(starts_with("STAI_state"), names_to = "measurement") %>%
    mutate(
        measurement = recode_factor(measurement, 
                                    "STAI_state1_total" = "before", 
                                    "STAI_state2_total" = "after")
        )
```

```{r}
# temporarily write wide-format for jasp
if (!dir.exists("tmp_outputs")) { dir.create("tmp_outputs") }
df %>% 
    select(c("label", starts_with("STAI_state"))) %>%
    write_tsv('tmp_outputs/state_anxiety_ctg.tsv')
```

### Classical ANOVA

```{r tags=c()}
a_state_anxiety <- aov_ez(
    id = "label", 
    dv = "value",
    data = state_anxiety,
    within = "measurement"
)

a_state_anxiety
```

## STAI Trait - mean

```{r}
trait_anxiety <- df %>%
    select(c("label", "STAI_trait_total"))
```

```{r}
mean(trait_anxiety$STAI_trait_total)
```